import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import manifest from './fixtures/secForm4Real/manifest.json';
import expected from './fixtures/secForm4Real/expected.json';
import { parseForm4Xml } from './secForm4Parser';
import { analyzeForm4Positions } from '../calculations/secForm4Position';

// Offline only. Expectations were extracted independently with System.Xml/XPath,
// reviewed against the raw documents, and frozen; never generated by this parser.
const documents = manifest.map(m => {
  const bytes = readFileSync(new URL(`./fixtures/secForm4Real/${m.file}`, import.meta.url));
  const xml = bytes.toString('utf8');
  const result = parseForm4Xml(xml, {
    filingId: m.accession, accessionNumber: m.accession, sourceIdentifier: m.sourceUrl,
    sourceUrl: m.sourceUrl, filingUrl: m.filingUrl, filedAt: m.filedAt,
    retrievedAt: m.retrievedAt, origin: 'public',
  });
  const e = expected.find(e => e.file === m.file)!;
  return { m, bytes, xml, result, e };
});

for (const { m, bytes, xml, result, e } of documents) {
  test(`real SEC ${m.file}: original bytes, provenance and independently recorded identity/date fields`, () => {
    assert.equal(createHash('sha256').update(bytes).digest('hex'), m.sha256);
    assert.match(m.sourceUrl, /^https:\/\/www\.sec\.gov\/Archives\/edgar\/data\//);
    assert.ok(e);
    assert.ok(result.source, JSON.stringify(result.issues));
    const s = result.source;
    assert.equal(s.filingId, m.accession);
    assert.equal(s.accessionNumber, m.accession);
    assert.equal(s.provenance.sourceUrl, m.sourceUrl);
    assert.equal(s.provenance.filingUrl, m.filingUrl);
    assert.equal(s.provenance.origin, 'public');
    assert.equal(s.issuer.name, e.issuer);
    assert.equal(s.issuer.name, m.issuer);
    assert.equal(s.issuer.identifier?.value, e.issuerCik);
    assert.equal(s.issuerTicker, e.ticker);
    assert.equal(s.filingType, e.form);
    assert.equal(s.filingType, m.documentType);
    assert.equal(result.periodOfReport, e.period);
    assert.equal(result.dateOfOriginalSubmission, e.originalSubmission);
    assert.equal(s.dates.filedAt, m.filedAt);
    assert.equal(s.dates.retrievedAt, m.retrievedAt);
    assert.equal(s.dates.publishedAt, null);
    assert.equal(s.dates.periodEnd, null);
    assert.equal(s.dates.asOfDate, null);
    assert.equal(s.amendment.kind, e.form === '4/A' ? 'unknown' : 'original');
    assert.equal(s.amendment.previousFilingId, null);
    assert.equal(s.issuer.verified, false);
    assert.match(xml, /<ownershipDocument>/);
  });

  test(`real SEC ${m.file}: all reporting owners and independent optional role flags`, () => {
    assert.ok(result.source);
    assert.deepEqual(result.source.reportingOwners.map(o => ({
      cik: o.identity.identifier?.value ?? null, name: o.identity.name,
      director: o.relationship.director, officer: o.relationship.officer,
      tenPercentOwner: o.relationship.tenPercentOwner, other: o.relationship.other,
      officerTitle: o.relationship.officerTitle, otherText: o.relationship.otherText,
    })), e.owners);
    for (const o of result.source.reportingOwners) {
      assert.equal(o.identity.kind, 'unknown');
      assert.equal(o.identity.verified, false);
      assert.ok(o.relationship.evidence[0].locator?.includes('reportingOwnerRelationship'));
    }
    assert.deepEqual(result.source.filers, []);
  });

  test(`real SEC ${m.file}: every Table I scalar, footnote and unsupported row count matches XML`, () => {
    assert.ok(result.source);
    assert.deepEqual(result.source.transactions.map(r => ({
      securityTitle: r.security.title, transactionDate: r.transactionDate,
      code: r.transactionCode, swap: result.transactionSemantics[r.rawSourceId].equitySwapInvolved,
      shares: r.shares, price: r.price, direction: r.acquisitionDisposition,
      holdingsAfter: r.ownershipAfter,
      ownership: r.ownershipType === 'direct' ? 'D' : r.ownershipType === 'indirect' ? 'I' : null,
      nature: r.ownershipNature, footnoteIds: r.footnoteReferences.flatMap(f => f.ids),
    })), e.rows);
    assert.deepEqual(result.source.footnotes, e.footnotes);
    assert.deepEqual(result.unsupported, e.unsupported);
    result.source.transactions.forEach((r, index) => {
      assert.equal(r.rawSourceId, `non-derivative-${index + 1}`);
      const location = `/ownershipDocument[1]/nonDerivativeTable[1]/nonDerivativeTransaction[${index + 1}]`;
      assert.equal(r.evidence[0].locator, location);
      for (const ref of r.footnoteReferences) {
        assert.ok(ref.field.startsWith(`${location}/`));
        assert.ok(ref.ids.every(id => result.source!.footnotes.some(n => n.id === id)));
      }
      assert.deepEqual(r.ownerAttribution, { references: [], status: 'unknown', evidence: [] });
    });
  });

  test(`real SEC ${m.file}: safe actions, unavailable value, no invented market venue or owner allocation`, () => {
    const analysis = analyzeForm4Positions(result);
    assert.equal(analysis.rows.length, e.rows.length);
    assert.equal(analysis.coverage, 'UNKNOWN');
    analysis.rows.forEach((r, i) => {
      const row = e.rows[i];
      const action = row.code === 'P' && row.direction === 'A' ? 'BUY'
        : row.code === 'S' && row.direction === 'D' ? 'SELL' : 'OTHER';
      assert.equal(r.action, action);
      assert.equal(r.marketVenue, 'unknown');
      assert.equal(r.transactionValue, null); // XML does not prove quantity/price units.
      assert.equal(r.transactionCode, row.code);
      assert.equal(r.holdingsAfter, row.holdingsAfter);
      assert.equal(r.ownerAttribution.status, 'unknown');
      assert.ok(r.issues.includes('quantity_or_price_basis_unconfirmed'));
    });
    assert.deepEqual(analyzeForm4Positions(result), analysis);
  });
}

test('real SEC coverage: P/S/M/F/G, multi-owner, ten-percent, direct/indirect, Table II and holdings-only', () => {
  assert.equal(documents.length, 8);
  assert.deepEqual([...new Set(expected.flatMap(e => e.rows.map(r => r.code)))].sort(), ['F','G','M','P','S']);
  assert.ok(expected.some(e => e.owners.length === 2));
  assert.ok(expected.some(e => e.owners.some(o => o.tenPercentOwner)));
  assert.ok(expected.some(e => e.rows.some(r => r.ownership === 'I')));
  assert.ok(expected.some(e => e.unsupported.derivativeTransactions > 0));
  assert.ok(expected.some(e => e.unsupported.nonDerivativeHoldings > 0));
});

test('real SEC partial is explicit for omitted flags/unsupported rows; only complete supported samples parse fully', () => {
  for (const { m, result } of documents) {
    const fullyParsed = ['docusign-sale.xml','docusign-director-sale.xml'].includes(m.file);
    assert.equal(result.status, fullyParsed ? 'parsed' : 'partial');
    assert.ok(result.issues.every(i => ['missing_boolean','unsupported_rows'].includes(i.code)));
  }
});

test('real SEC schemas X0508/X0609 retain supported data despite empty containers and extra legal fields', () => {
  assert.deepEqual([...new Set(expected.map(e => e.schemaVersion))].sort(), ['X0508','X0609']);
  const newer = documents.find(d => d.m.file === 'victoria-amendment.xml')!;
  assert.match(newer.xml, /<issuerForeignTradingSymbol><\/issuerForeignTradingSymbol>/);
  assert.match(newer.xml, /<rptOwnerNonUSAddressFlag>false<\/rptOwnerNonUSAddressFlag>/);
  assert.match(newer.xml, /<footnotes><\/footnotes>/);
  assert.match(newer.xml, /<remarks>This Form 4 is being amended/);
  assert.equal(newer.result.source!.transactions[0].shares, 633);
  assert.equal(newer.result.source!.reportingOwners[0].relationship.officer, null);
});

test('real SEC price footnotes remain numeric observations, never verified total consideration', () => {
  const d = documents.find(d => d.m.file === 'ault-amendment.xml')!;
  const row = d.result.source!.transactions[0];
  assert.equal(row.price, 0.189);
  assert.ok(row.footnoteReferences.some(f => f.field.endsWith('/transactionPricePerShare[1]')));
  assert.equal(analyzeForm4Positions(d.result).rows[0].transactionValue, null);
  const plain = documents.find(d => d.m.file === 'victoria-amendment.xml')!;
  assert.equal(plain.result.source!.transactions[0].price, 45.86);
  assert.equal(analyzeForm4Positions(plain.result).rows[0].transactionValue, null);
});
