import Link from 'next/link';
import { notFound } from 'next/navigation';
import { marketDataService } from '@/lib/services/marketDataService';
import { aiAnalysisService } from '@/lib/services/aiAnalysisService';
import { newsService } from '@/lib/services/newsService';
import { Card,Change,NewsList } from '@/components/ui/common';
import { PriceChart } from '@/components/stock/PriceChart';
import { number } from '@/lib/utils/formatters';
export default async function Stock({params}:{params:Promise<{symbol:string}>}){const {symbol}=await params;const s=await marketDataService.getSecurity(symbol);if(!s)notFound();const [history,ai,news]=await Promise.all([marketDataService.getHistory(s.symbol),aiAnalysisService.getAnalysis(s.symbol),newsService.getNews(s.symbol)]);return <><Link href="/dashboard" className="text-link">← 返回市場總覽</Link><div className="page-heading stock-heading"><div><p className="eyebrow">{s.market==='TW'?'台股':'美股'} / {s.type==='etf'?'ETF':'個股'} 研究</p><h1>{s.name} <span className="muted">{s.symbol}</span></h1><p className="muted">09/10 13:30（台北）· 模擬資料</p></div><div className="stock-price"><strong>{number(s.price)} <small>{s.currency}</small></strong><Change value={s.changePercent}/><span className="muted">漲跌 {s.change>=0?'+':''}{number(s.change)}</span></div></div><div className="detail-grid"><Card title="價格走勢"><PriceChart data={history} currency={s.currency}/></Card><Card title="基本資料"><dl className="fundamentals">{[['市場',s.market==='TW'?'台灣':'美國'],['類型',s.type==='etf'?'指數股票型基金':'股票'],['產業／投資範圍',s.sector],['交易幣別',s.currency],['模擬殖利率',`${s.dividendYield}%`]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></Card></div><div className="bottom-grid"><Card title="AI 研究摘要"><p>{ai.summary}</p><div className="factors"><div><h3>有利因素</h3><ul>{ai.bullFactors.map(t=><li key={t}>{t}</li>)}</ul></div><div><h3>不利因素</h3><ul>{ai.bearFactors.map(t=><li key={t}>{t}</li>)}</ul></div></div><div className="risk"><h3>風險提醒</h3>{ai.riskAlerts.map(t=><p key={t}>{t}</p>)}</div><p className="disclaimer">{ai.disclaimer}</p></Card><Card title="相關模擬新聞"><NewsList items={news}/></Card></div></>}
